# k2

version: "3.6"

services:
  # Nginx Web Application
  webserver:
    container_name: k2-webserver
    image: nginx:alpine
    working_dir: /var/www/k2
    restart: always
    volumes:
      - .:/var/www/k2
      - ./docker/nginx/nginx-production.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /ssl:/ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=k2.amarassist.com.br
  # PHP-FPM
  php-fpm:
    container_name: k2-php-fpm
    build:
      context: docker/php-fpm
      args:
        PHP_VERSION: 8.1
    working_dir: /var/www/k2
    restart: always
    volumes:
      - .:/var/www/k2
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
  # Redis
  redis:
    container_name: k2-redis
    image: redis:alpine
    restart: always
    volumes:
      - k2-redis-data:/data
    ports:
      - "6379:6379"

volumes:
  # redis-data
  k2-redis-data:
    driver: local
